### ISSUE TITLE
binary file can use git lfs

### ISSUE THREAD

**Issue by VZIKL** [Kenan2000/Otopack-Mods-Updates#1]
Info: https://git-lfs.github.com/ 
create .gitattributes file with:
git lfs track "*.ogg"

**Comment by Kenan2000** [comment]
@VZIKL Can you elaborate and give me a proper example?

**Comment by Kenan2000** [comment]
@VZIKL better now?Check the files, the .gitattributes file contains this piece of code now: 

*.ogg filter=lfs diff=lfs merge=lfs -text

**Comment by Kenan2000** [comment]
Closed because LFS is included properly now thanks to @VZIKL's suggestions
