### ISSUE TITLE
DinoMod support

### ISSUE THREAD

**Issue by LyleSY** [Kenan2000/Otopack-Mods-Updates#12]
The sounds are great, but dinosaurs are sadly silent. Some nice stomps, grunts, and roars would be good

**Comment by Kenan2000** [comment]
@LyleSY Here, check this file https://github.com/Kenan2000/Otopack-Mods-Updates/blob/master/Otopack%2BModsUpdates/effects.json, cats and dogs sounds, but these can be heard only cause monsters have "PARROT" flag in these cases, if they don't, regular monster combat sounds cannot be tied to dinos, they are hardcoded, only "PARROT" ones, if you are interested in reworking Dinomod monsters to add these them to dinosaurs, manage to find, edit and convert to .ogg sound files with dinosaurs roaring sounds as well, I will make sure to include them hopefully, but it's plenty of work as well
