### ISSUE TITLE
Remove Rhythmic Beat in Otopack+ModsUpdates/env/ambience_and_weather/indoors.ogg

### ISSUE THREAD

**Issue by redcrate** [Kenan2000/Otopack-Mods-Updates#26]
There is a rhythmic beat in the indoor ambient sound effect.

Otopack+ModsUpdates/env/ambience_and_weather/indoors.ogg

Personally, I find this to be very annoying given that a character will spend a lot of time "indoors."

It's fine to have beats and music, but they should obviously be in the music section (which I disable in the game settings and they cause me no bother).

I propose altering the indoor ambient sound to remove this beat. I have manually removed this sound file and replace it with another, but it's manual hassle which I would rather not do for an otherwise excellent sound-pack.

I have attached a small amplified loop of the indoors sound in hopes that you can hear the beat as well, the entire thing contains numerous beats, but it's most noticeable at around the 8 second mark.

https://user-images.githubusercontent.com/85591702/133555700-806d3232-6554-4a6e-b567-f1027f45fed8.mp4

**Comment by Kenan2000** [comment]
Hopefully fixed in latest update
