### ISSUE TITLE
github out of date links

### ISSUE THREAD

**Issue by robotic-gamer** [Kenan2000/Otopack-Mods-Updates#27]
not sure if this is the right place but some problems with github links.
Link to legendary tileset by SomeDeadGuy
https://github.com/SomeDeadGuy/UndeadPeopleTileset 
is dead
possible replacement.
https://github.com/Theawesomeboophis/UndeadPeopleTileset

also the link to the modding discord is expired.

**Comment by Kenan2000** [comment]
@robotic-gamer Hopefully fixed in latest update
