### ISSUE TITLE
indoors.ogg plays when outside. 

### ISSUE THREAD

**Issue by notherdimension100** [Kenan2000/Otopack-Mods-Updates#33]
More specifically happens when i enter then exit a vehicle, it will permanantly play until i log out and reload the world. Great soundpack, its just that this file is annoying to hear 24/7.

https://user-images.githubusercontent.com/100170124/155036576-b377fe22-df6d-4d8f-9ee5-f971dcc964c5.mp4

.

**Comment by Kenan2000** [comment]
Hopefully fixed in latest update
