### ISSUE TITLE
Shriek / Wail sound

### ISSUE THREAD

**Issue by KurzedMetal** [Kenan2000/Otopack-Mods-Updates#36]
I'd love to have more sounds for monster specific attacks, specially when they should interesting repercussions to the player, like Shrieker's shriek / wail.

I found this sound for a shriek: https://www.videvo.net/sound-effect/zombie-cry-shriek-pe981203/262773/

EDIT: Previous sound is awesome, but seems you need to pay to download it / use it. I found this other one, not as great but is CC0 https://freesound.org/people/wintertriangles/sounds/179893/

I found in the code the ids seems to be "shout" and variant "shriek" and "wail".

Could you add it?

**Comment by Kenan2000** [comment]
Considering that you have added these sounds to another soundpack, you can probably understand that it is best to not copy sounds from other soundpacks to retain originality of each, but I appreciate your suggestions as well
