### ISSUE TITLE
Flintlock Rifle has no sound.

### ISSUE THREAD

**Issue by WreckingAbandon** [Kenan2000/Otopack-Mods-Updates#46]
Both reloading and firing.

**Comment by WreckingAbandon** [comment]
The Misericorde from Arcana also has no sound. For now I just made it both use the standard flintlock sound.

**Comment by Kenan2000** [comment]
Maintenance of this version of Otopack is my secondary priority which I mostly try to update if there are new mods available or if a huge amount of weapons is added to an existing mod so I suggest you to make pull requests for small tweaks along with additions yourself provided that you can do this work hopefully as well
