### ISSUE TITLE
Compound hunting bow weapon sound bug

### ISSUE THREAD

**Issue by BjoHart** [Kenan2000/Otopack-Mods-Updates#49]
Hello all together. I hope someone is reading this.
There is a problem with the sound when the hunting bow is shot and a bow dampening set is attached.
The sound then becomes that of a firearm.
Could someone fix this?

**Comment by Kenan2000** [comment]
@BjoHart Hello there, please, look at this older issue that was closed https://github.com/Kenan2000/Otopack-Mods-Updates/issues/6 , as you see, I have no idea how to fix this 

Still, feel free to ask me any other questions if you have any hopefully as well
