### ISSUE TITLE
Horse Engine

### ISSUE THREAD

**Issue by yoba712** [Kenan2000/Otopack-Mods-Updates#5]
The sound of a harnessed horse works as if it were a car engine. It's funny, but I would like the sounds of a horse.

**Comment by Kenan2000** [comment]
@yoba712 the soundpack actually contains unused horse neighing horse - you are quite lucky in this case :-) just I'm not sure what `id` or `variant` harnessed horse uses, can you `examine` it just like any vehicle and tell me the ID of whatever "engine" it's using - the ID of the horse in a vehicle form basically, this way I'll be able to do bind horse neighing sounds to the harnessed horse "engine" variant

**Comment by yoba712** [comment]
Not really sure how to look at the horse ID, but here's a screenshot if it helps. https://i.gyazo.com/b868c9f2768ae89d5a8699d41bc064f3.png

**Comment by Kenan2000** [comment]
@yoba712 thanks for providing the picture :-) , well, there is a small problem here - if I add a horse sound to this item, it will ALWAYS play a horse sound NO MATTER what animal you attach to the harness - it may be a large dog as well, a dinosaur if you're playing with Dinomod - and in each of these cases it will always emit a horse sound, I think neither you nor other players are going to like this so maybe we'd rather not add any specific sound to this item or else it's gonna cause lots of inconsistencies like I've already explained

**Comment by yoba712** [comment]
It is possible, as an option, to add a neutral sound of stomping, for example, just a sound of steps like a character. Or turn off the sound of the engines completely.

**Comment by Kenan2000** [comment]
> It is possible, as an option, to add a neutral sound of stomping, for example, just a sound of steps like a character. Or turn off the sound of the engines completely.

Turning the sound of the engine off is impossible - it is hardcoded - a sound of stomping...I'll try to add it and see if it works

**Comment by Kenan2000** [comment]
@yoba712 check this out and test it, if you can, please https://github.com/Kenan2000/Otopack-Mods-Updates/commit/8dc8f26596a832f097164b3c052cace5d0bbfaf6 - added a sound for `yoke_harness` - should be working correctly but not entirely sure, have not tested it

**Comment by yoba712** [comment]
Ok, I noticed a few things at once - the horse still has the sound of the engine starting. When driving, there is no driving sound, while there is a gear shift sound.
And yet, I do not know why, but the sounds of doors and windows opening, any, disappeared.

**Comment by Kenan2000** [comment]
> Ok, I noticed a few things at once - the horse still has the sound of the engine starting. When driving, there is no driving sound, while there is a gear shift sound.
> And yet, I do not know why, but the sounds of doors and windows opening, any, disappeared.

There is no galloping sound at all?No internal/external engine sound?

**Comment by yoba712** [comment]
No, only engine starting sound

**Comment by Kenan2000** [comment]
> No, only engine starting sound

And before the update?Were the engine sounds present while driving - that is, not only when starting to "drive" the horse, but during driving itself as well?

**Comment by yoba712** [comment]
Yes, there were sounds when driving, driving sounds and speed changes

**Comment by Kenan2000** [comment]
@yoba712 here's another commit - https://github.com/Kenan2000/Otopack-Mods-Updates/commit/0ac1d028aa917274b87c170cb4ba8d76918a4071 - done more tweaking, check it out now - if this does not work - I don't know what to do then

**Comment by yoba712** [comment]
Now the engine start sound has also disappeared. But without the sounds of transport with a horse is still better than with the sound of a motor.
Thank you very much for your work.
