### ISSUE TITLE
Portal Storm

### ISSUE THREAD

**Issue by evilbananas** [Kenan2000/Otopack-Mods-Updates#52]
Sounds effects for Portal Storms do not turn off after the Portal Storm has subsided.

**Comment by Kenan2000** [comment]
Hmm, this is tied to functionality only of core game's hardcode which means that developers themselves need to look into this to fix this issue that you mention. The only thing that has been added to this version of Otopack is sound of portal storms itself along with simple JSON which tells game to activate this sound if there are any nearby, no conditions to turn off this sound upon portal storms subsiding which only means that this issue that you mention can only be edited by developers in their game version honestly
