### ISSUE TITLE
Ar 15 and relatives can't produce reload sounds

### ISSUE THREAD

**Issue by Aeiouuu01234** [Kenan2000/Otopack-Mods-Updates#53]
My guessing is that, because of the new upper receiver mods the "modular_ar15" doesn't know what sound files to call, I know that's the id that should be used since texture packs call for that one too

**Comment by Kenan2000** [comment]
Maintenance of this version of Otopack is my secondary priority which I mostly try to update if there are new mods available or if a huge amount of weapons is added to an existing mod so I suggest you to make pull requests for small tweaks along with additions yourself provided that you can do this work hopefully as well
