### ISSUE TITLE
Dampened bow sounds like gun.

### ISSUE THREAD

**Issue by Roet718** [Kenan2000/Otopack-Mods-Updates#6]
With this soundpack bows make wonderful little pwing sound when shooting them, that is until a dampening kit is installed. the dampening kit is supposed to reduce the noise of the bow but in this pack it makes the bow sound like a gunshot.

**Comment by Kenan2000** [comment]
@Roet718 I cannot really promise that I'll be able to fix this one - first of all, I would like to know the exact name and possibly see the picture of the bow that you're using and modifying - the soundpack gun sound system is something similar to this: `"variant": "gun_id", "sound_id": "fire_gun/fire_gun_distant/reload"`

So in this case it must be that the game strangely mistakenly changes the `variant` from the bow to some gun when modifying it and equipping it with an accessory - this is a totally strange behavior and it is pretty much impossible to trace or figure out to what exactly it changes it's `variant`

**Comment by Roet718** [comment]
Well ive noticed it on several bows. Right now im seeing it on the compound hunting bow with the bow dampening kit installed.
![Compound hunting bow](https://user-images.githubusercontent.com/19896899/100050989-49dbd500-2de0-11eb-93d4-9592514f7d9c.PNG)
![Bowdampeningkit](https://user-images.githubusercontent.com/19896899/100050992-4d6f5c00-2de0-11eb-82fc-2159a40e3749.PNG)

**Comment by Kenan2000** [comment]
![555555555](https://user-images.githubusercontent.com/43505148/100051352-2000cd80-2e35-11eb-9a21-359aa902a5c1.png)
![33333333333](https://user-images.githubusercontent.com/43505148/100051361-24c58180-2e35-11eb-84ba-456ce5068797.PNG)

Kindly, take a look at these pictures - this is the way the ENTIRE ranged weapons sound JSON system works - there is no more JSON code related to the compound hunting bow - that is, I am not able to do anything with the bow apart from these 3 code blocks - these are the only things I can change, what's happening in this case is that for some reason it, I believe, somehow changes the `variant` dynamically from `compbow` to whatever that's using gun sounds - I have no idea why and this could be a vanilla issue - have you tried replicating this in Bright Nights fork maybe?This could really be a game issue that no one is aware of, but considering that this soundpack is not mainlined and purely volunteer work, the chances of this issue - considering how miniscule it is - being fixed are not that high

**Comment by Roet718** [comment]
I'm not familiar with the bright nights fork. Thats alright. Thanks for looking into it.

**Comment by Kenan2000** [comment]
Closing this for now because no idea how to fix this
