### ISSUE TITLE
What is the sound that step into shallow water

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/Otopack-Mods-Updates#7]
That sounds very bad...A sharp noise, maybe ogg file is corrupted?

Cataclysm-DDA experimental build #11292

**Comment by Kenan2000** [comment]
@linonetwo I am on #11292 either and have just tested every single shallow water terrain by spawning them via debug menu and walking over them repeatedly back and forth - no sharp noises, everything is fine, I'm not sure exactly what the problem you're experiencing is about

**Comment by linonetwo** [comment]
Thank you for the fast response, maybe the problem is that I'm in MacOS Big Sur?

See this .mov


https://user-images.githubusercontent.com/3746270/103122291-8db14b00-46ba-11eb-868d-11c7286a6082.mov

Actually, I tried to redownload your sound pack, and the problem exists.

Also, I tried to listen step-water.ogg from 1-6, they sound good, but bad in the game...

**Comment by linonetwo** [comment]
The first time step into the water seems fine, but leaving water and later step will be noise...

**Comment by Kenan2000** [comment]
@linonetwo Hmm, it could be due to this particular version, or you using Mac (even though, I am totally oblivious in terms of why it's happening on Mac in particular), anyway, here is the JSON which corresponds to the water walking sounds:

```{
        "type": "sound_effect",
        "id" : "plmove",
        "variant" : "walk_water",
        "volume" : 50,
        "files" : [
            "player/walk/walk_water1.ogg",
            "player/walk/walk_water2.ogg",
            "player/walk/walk_water3.ogg",
            "player/walk/walk_water4.ogg",
            "player/walk/walk_water5.ogg",
            "player/walk/walk_water6.ogg"
        ]
    },```

**Comment by linonetwo** [comment]
Very strange, I tried to replace each file with these four ogg files, the noise still remains, but if I change all 4 of them, then the noise is gone.

[Archive.zip](https://github.com/Kenan2000/Otopack-Mods-Updates/files/5741785/Archive.zip)

**Comment by linonetwo** [comment]
Directly open them in the chrome won't have the noise.

**Comment by linonetwo** [comment]
And the sound that hits monster sometimes also got the same noise.
