### ISSUE TITLE
Git LFS may exceed the download limit

### ISSUE THREAD

**Issue by GeekDuanLian** [Kenan2000/Otopack-Mods-Updates#8]
Whether I use `Download ZIP` or `git clone`, some of the files I get are similar to this, such as `music/yig_cryochamber1.ogg`
```
version https://git-lfs.github.com/spec/v1
oid sha256:de744d73ec9f242c15d6ebf07651fac94876a2df6b99bc8b052ef82901ef0c32
size 10525092
```
I checked, it may be that the download data is exhausted, maybe it is directly stored in git, there may not be such a restriction.

**Comment by Kenan2000** [comment]
@GeekDuanLian Any possible ideas or suggestions to what can be done to fix this?

**Comment by GeekDuanLian** [comment]
@Kenan2000
Just like other files, `git add`,  `commit` and then `git push`.
Github only limits the size of a single file to be less than 100MB. Anything smaller than this limit can be directly `git add`.
Ref: https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota

**Comment by GeekDuanLian** [comment]
There is no download limit for files stored in ordinary git, at least there is no hard limit.

**Comment by Kenan2000** [comment]
@GeekDuanLian Thank you for your advice, right now through sweat and hard work having spent like 2 hours I've managed to fully export all the LFS .ogg files and entirely get rid of them through git bash, can you test now if it's working for you?

**Comment by GeekDuanLian** [comment]
@Kenan2000 Tested, Everything is working now.
